### ISSUE TITLE
#include <Preferences.h> file missing

### ISSUE THREAD

**Issue by brinuk** [flyandi/SquidRID#1]
Compiling in Arduino get the message #include <Preferences.h> no such file or directory

**Comment by flyandi** [comment]
This only works on an ESP32 and you have to install the latest ESP32 board definition.

![image](https://github.com/flyandi/SquidRID/assets/329973/cc254f95-1a2c-49ca-8d69-e4c2e3ac5974)

**Comment by HoserMatt** [comment]
I have attempted to compile using several different ESP32s (to include the Adafruit Feather) and I am getting the same error (see below). Any assistance would be greatly appreciated. 

C:\...\SquidRID-master\SquidRID-master\fw\squidrid\squidrid.ino:39:10: fatal error: Preferences.h: No such file or directory
   39 | #include <Preferences.h>
      |          ^~~~~~~~~~~~~~~
compilation terminated.

exit status 1

Compilation error: Preferences.h: No such file or directory

**Comment by FPVGizmoFlying** [comment]
Having the same problem here.

**Comment by flyandi** [comment]
Curious - are u both using Arduino IDE or Platform IDE?

**Comment by FPVGizmoFlying** [comment]
I am using Arduino IDE 2.1.1

**Comment by flyandi** [comment]
I am using 2.1.0. Do me favor and just remove the `#include <Preferences.h>` and see if it compiles?

**Comment by FPVGizmoFlying** [comment]
I tried that and it then has other files missing like WiFi.h and others.

**Comment by flyandi** [comment]
Oh in that case you don't have the esp32 platform definitions installed or you didn't select the right board from the board menu.

**Comment by flyandi** [comment]
I assume it got resolved? If not comment again .

**Comment by kotovasia5120** [comment]
I have the same problem in Arduino IDE

**Comment by flyandi** [comment]
U have to install the ESP32 2.x definitions NOT ESP 3.x definitions.  (Latest in Arduino IDE is 3.x) - Go to the ESP32 package and select the latest 2.x version.

**Comment by kotovasia5120** [comment]
This error originally appeared on 2.x
had to switch to 3.x
And the problem is not in your repository, I found this topic through search.

**Comment by flyandi** [comment]
I think certain ESP32's don't use that one as they don't have support for it. Not sure.

**Comment by kotovasia5120** [comment]
> I think certain ESP32's don't use that one as they don't have support for it. Not sure.

I use esp32 s3 and last week it compiled without problems

**Comment by GMaska** [comment]
Switched to 2.9 for esp32 definitions and compiled fine under DOIT ESP32 DEVKIT V1
