### ISSUE TITLE
Clarification: RemoteID and/or DroneID?

### ISSUE THREAD

**Issue by wspch0p** [flyandi/SquidRID#12]
Hey,

does this project also spoof/broadcast DJI's DroneID data (Aeroscope detectable) or (FAA style) Remote ID only?

Source indicates opendroneid is used, yet I'm unsure if DJI's DroneID is using the same protocol?

A sample project claiming to spoof Aeroscope detectable DroneID data:
https://github.com/DJISDKUser/ESP8266_DJI_DroneID_Throwie

Kindly asking for clarification.

**Comment by flyandi** [comment]
Howdy. This is for the FAA remoteID only.  The project you linked uses a static wifi package that probably can fool aeroscope .. not sure.

squidrid is different as all packages are assembled at runtime and filled in with your test values .
