### ISSUE TITLE
Compilation error: 'system_event_t' has not been declared

### ISSUE THREAD

**Issue by RaLLy19v** [flyandi/SquidRID#13]
While verifying code i got an Compilation error: 'system_event_t' has not been declared.  Does anyone know how to troubleshoot this?

**Comment by flyandi** [comment]
In which line?

**Comment by flyandi** [comment]
Looks like `system_event_t` was removed in IDF version 4.0. I could only compile it on the 2.x versions of the ESP32 board definition as it looks like 3.x is using IDF 4.0 and 2.x versions use IDF 3.0.

**Comment by RaLLy19v** [comment]
Board: Seeed Studio Xiao 32c3

Complete Text:

squid_network.h:47:33: error: 'system_event_t' has not been declared
   47 | esp_err_t event_handler(void *, system_event_t *);
      |                                 ^~~~~~~~~~~~~~
squid_instance.cpp:45:
squid_network.h:47:33: error: 'system_event_t' has not been declared
   47 | esp_err_t event_handler(void *, system_event_t *);
      |                                 ^~~~~~~~~~~~~~
squid_network.h:47:33: error: 'system_event_t' has not been declared
   47 | esp_err_t event_handler(void *, system_event_t *);
      |                                 ^~~~~~~~~~~~~~
squid_network.cpp: In member function 'void Squid_Network::transmit_bt(Squid_Network_Message*)':
squid_network.cpp:138:9: error: 'esp_base_mac_addr_set' was not declared in this scope
  138 |         esp_base_mac_addr_set(message->mac);
      |         ^~~~~~~~~~~~~~~~~~~~~
squid_instance.h:51,
squid_network.h:47:33: error: 'system_event_t' has not been declared
   47 | esp_err_t event_handler(void *, system_event_t *);
      |                                 ^~~~~~~~~~~~~~

exit status 1

Compilation error: 'system_event_t' has not been declared

**Comment by RaLLy19v** [comment]
@flyandi Thank you...that did it...2.0.7 worked. Thank you

**Comment by flyandi** [comment]
Perfect. Closing this.

**Comment by owengrey** [comment]
why not just fix your code so others might be able to try it?

**Comment by flyandi** [comment]
The code was written for IDF 3.0 and not IDF 4.0 - plain simple. I will accept PR's for IDF 4.0 adoption of course.
