### ISSUE TITLE
Crashes iphone Drone Scanner app and Dronetag app

### ISSUE THREAD

**Issue by ipocalypse** [flyandi/SquidRID#2]
The apps will run till it detects a drone. Very quickly after detection the app crashes. All info appears to be showing up in the app before it crashes.

**Comment by flyandi** [comment]
Not really sure if that has anything to do with SquidRID.

Can you send links to those apps please? I am on Android - maybe someone else on iPhone can chime in here.

I have Done Scanner running on Android for hours without issues.

**Comment by ipocalypse** [comment]
App seems to run without issue if the esp32 is powered off. 
If I had to guess I would say the apps are getting the packets too quickly. I tested it while walking away from the esp32. When I got to the edge of the range it got 1 packet and did not crash. I started walking back and as soon as it got in range again it crashed the app. 
https://apps.apple.com/gb/app/drone-scanner/id1644548782
This one will allow me to see the info before it crashes. Packet count is very rapid.

**Comment by flyandi** [comment]
Interesting. I actually run packages much slower than RemoteID usually requires it. A real RemoteID will probably even more crash it .

**Comment by ipocalypse** [comment]
Well that was just a theory as it did not crash when it only got 1 packet. Not sure what it could be then. But both the apps I can find for iphone do the same thing. They run fine until I connect power to the esp32.. then they both crash. I have not found any other app for the iphone that detects RID.

**Comment by flyandi** [comment]
I wonder if it's a non-sanitized string :-D - that would be funny. Can you send me your configuration? Either connect via serial and send command "$D" or go to the configurator and open the console and look for the response for $D, like: [serial] received $D|1007|   and copy or screenshot it.

**Comment by ipocalypse** [comment]
$D|1005|1792C000000000000121004|uAvionix pingRID|Military|2|1|38.240002|-122.620003|0|38.240002|-122.620003|100|0|8|C0:D4:AA:67:0F:A0|1|38.258133|-122.630768|500|5|0|

**Comment by ipocalypse** [comment]
$D|1005||UAS_NO_NAME|Recreational|1|1|0.000000|0.000000|0|0.000000|0.000000|100|100|8|84:CE:16:6C:FD:48|0|0.000000|0.000000|1500|5|0|

**Comment by flyandi** [comment]
They both look good and I tested them both - no issue on Android. I need someone else to test this as I don't have an iphone here.

**Comment by ipocalypse** [comment]
![IMG_5736](https://github.com/flyandi/SquidRID/assets/1031234/634d66ee-ccdf-4689-bcae-6cdfcd025e06)

**Comment by ipocalypse** [comment]
Was able to get a screen shot before it crashed.

**Comment by ipocalypse** [comment]
Just tried both apps on an ipad as well with the same results. Crash after detecting the esp32's drones

**Comment by flyandi** [comment]
I had a chance to test it on an iPhone and sure enough it fails. Looks like it's a common problem not just with SquidRID. Not sure how to resolve.

**Comment by truglodite** [comment]
Have you tested iOS devices with an actual RID, like DJI?

If it also crashes with 'real devices', then it seems it would have to be the app.

**Comment by ipocalypse** [comment]
![IMG_5744](https://github.com/flyandi/SquidRID/assets/1031234/d46021fc-3279-4930-a86d-f0ab4845296f)

Maybe it has something to do with the error on the operator ID?

**Comment by flyandi** [comment]
The frames are not sent in order. So any receiver will have to collect and wait till a full set of frames are collected.  Again I have seen many people complain that this app is not working on iOS. On Android there are no issues.

There is very little I can do.

**Comment by ipocalypse** [comment]
Ohh i was not complaining just trying to help isolate the issue. Appreciate all your work for the cause!

**Comment by Stevofpv** [comment]
Awesome job on the app.  I'm very new to coding so there was a bit of a learning curve.  It's pretty funny that it does indeed crash the RID apps...lol
