### ISSUE TITLE
Web installer

### ISSUE THREAD

**Issue by mpistol** [flyandi/SquidRID#3]
Bin file with a web installer would be great

**Comment by truglodite** [comment]
I think there was errors during my install of nodejs that made the local web not work. When I run `start npm` it says:

```> web@0.1.0 start
> react-scripts start

'react-scripts' is not recognized as an internal or external command,
operable program or batch file.
```

I'm a newb with nodejs... all I can say is I think I saw windows protected folders pop up during install, which usually isn't good and results in missing files etc.

**Comment by flyandi** [comment]
Did u you run `npm install` or `yarn`? You have to download all the dependencies. 

Also the configurator is exposed at https://squidrid.flyandi.net/

**Comment by truglodite** [comment]
That was all I was missing... running `npm install` did the trick, and now I'm able to config locally. FWIW, the online config at squidrid.flyandi.net has what appears to be a bug in pest mode where the spawned drones occur outside of the yellow radius, and the spawn points appear to consistently drift north west. When I run it locally, all spawns stay within the yellow circle.

Not sure why that happens, but figured I'd bring it to your attention in case.

Thanks for sharing your impressive code btw!

[edit: NM... the same thing started happening on my local config instance as well... just took a few minutes, but now drones are spawning well outside the yellow circle locally as well. Another observation... it appears external is not working on the locally installed configurator. The button is missing, and gps setup in not in the profile page.]
