### ISSUE TITLE
External GPS documentation... or perhaps feature request.

### ISSUE THREAD

**Issue by truglodite** [flyandi/SquidRID#5]
So I've been playing with an old ublox 6m module and squidrid. There was no mention on how exactly it works in the docs, and after playing with it I have a couple questions:

Does external only use gps for operator location?

Is it possible to perhaps offset the operator location from an externally acquired position... like say 1000' away?

Is it possible to use external with pest mode... how?

Is the web configurator updated so external gps can be configured locally?

I do have my gps working with squidrid. In another bug report I mentioned external gps config is not working when the configurator is run locally (using code I downloaded fresh yesterday). I can only setup external gps using the online config.

**Comment by flyandi** [comment]
No the external GPS is used for the actual location. The operator location is still set manually in EXTERNAL mode. 

I actually have a branch that has dynamic shifting but haven't released yet.  I will try to get this done by this weekend. 

I am not sure why it won't work locally for you because I do all my testing locally and the repo is the one released online.

**Comment by truglodite** [comment]
OK I got it working locally... think I accidentally used an older download is all.

OTOH, external mode is not behaving as you described. When I have external mode active, if I change the operator location in profile, it keeps getting immediately replaced by the gps location. The "origin" coordinates keep being reset to 0's as well. Unfortunately I can't glean much info from the app, since I only have iphones in my household and the app just crashes. So I can't verify what info is actually being broadcast. I assume based on what is happening in profile, that squidrid replaces operator coords with gps location.

![Untitled](https://github.com/flyandi/SquidRID/assets/18795884/35cfe570-f512-40cb-81a3-5bed736a205a)

Edit: A bit more info... when external is being used, the map shows the yellow circle with blue center where the gps is located. When I hit "center" it goes to whatever that default island is in the middle of nowhere. When I hit the "op" button it takes me to the blue center. When I hit "loc" it takes me to where my ISP is located several miles away. Again, I can't find any trace of a "drone" located at the gps position, which I guess is how it's supposed to work.

**Comment by flyandi** [comment]
Can you start "FLY" in the mode buttons. In chrome tools it should tell you the location that comes in via serial `$C`. Is the GPS reflected in that?

I just tested it and it works as expected. I wonder if the parser can't read the GPS.

**Comment by truglodite** [comment]
I hit fly in external mode, and chrome tools console is showing this repeating message:
```
['$C', '0.000000', '0.000000', '38.xxxxxx', '-121.xxxxxx', '0.000000', '10.000000', '0', '0', '8', '1', '0']
```
...where 38/-121 are the gps coordinates with decimals redacted. The configurator shows that as the operator location. My local web server appears to be working identically to the online one right now.

Here is another one I got just after hitting fly/pause:

```
(31) ['$D', '1007', '1581F45T000000000000534', 'DJI MAVIC 3', 'N/A', '2', '1', '0.000000', '0.000000', '0', '0.000000', '0.000000', '10', '0', '8', 'C8:45:CB:21:EC:5A', '2', '38.xxxxxx', '-121.xxxxxx', '500', '5', '1', '9600', '4', '16', '0', '0', '0', '0', '0', '']
```

**Comment by truglodite** [comment]
OK it isn't parsing for some reason. I tried 9600 baud, then just nmea output, and it still isn't working.

**Comment by flyandi** [comment]
I have a raw flag - let me push it tonight to the repo so you can see the actual messages coming in from the GPS transmitter.

**Comment by flyandi** [comment]
baud rate might be wrong.

**Comment by truglodite** [comment]
I just went to 9600 baud, rebooted the gps, and ucenter shows it's ok. Here is another one I got just after hitting fly/pause:

```
(31) ['$D', '1007', '1581F45T000000000000534', 'DJI MAVIC 3', 'N/A', '2', '1', '0.000000', '0.000000', '0', '0.000000', '0.000000', '10', '0', '8', 'C8:45:CB:21:EC:5A', '2', '38.xxxxxx', '-121.xxxxxx', '500', '5', '1', '9600', '4', '16', '0', '0', '0', '0', '0', '']
```

**Comment by truglodite** [comment]
It was the ublox detailed configuration in ucenter after all. I reset to factory defaults, and it worked right off the bat. I appreciate your prompt and on point replies, and of course all your efforts in developing this code. Closing this...
