### ISSUE TITLE
Configurator settings not being respected

### ISSUE THREAD

**Issue by zeromonad** [flyandi/SquidRID#6]
I'm not sure if this is a bug with the firmware, the configurator or if it's me doing something wrong, but I am having trouble running pest and squid mode. The board I am running this on is an ESP-WROOM-32 using the ESP32 Dev board in Arduino IDE.

On pest mode, no matter what coordinates I set for the origin and operator in the configurator, it's setting them to a location I did not choose (a random place in Africa):
![Screenshot 2023-07-14 131727](https://github.com/flyandi/SquidRID/assets/24425249/8114e56c-e501-4c29-9ef6-17dc91cdb969)

On squid mode, when it's paused it looks like the operator and drone location is correct, but I cannot choose Fly mode because it will reset to Pest mode in the web interface.
Settings applied in the Tuning options:
![Screenshot 2023-07-14 125234](https://github.com/flyandi/SquidRID/assets/24425249/175f75ce-d5e2-4e01-a2f3-4e63e647ce5e)
Spawns correctly when paused in squid mode:
![Screenshot 2023-07-14 125255](https://github.com/flyandi/SquidRID/assets/24425249/3ef456f0-6f0e-4493-ab00-5733d5119744)
Setting keeps getting reset by itself:
![Animation](https://github.com/flyandi/SquidRID/assets/24425249/f53c2dbc-d69c-4729-ade7-ca69056849fe)

**Comment by Stevofpv** [comment]
Yeah.  The coordinates didn’t work for me either.  I have to click on the origin tab and do it that way.

**Comment by truglodite** [comment]
Just wanted to mention I have run this on an esp-wroom-32 (pcb antenna), and on an esp-wroom-32u (external antenna), and have no such issues. My only suggestion would be try clearing web cache/cookies if you are using the online configurator. Also you can try installing the web config locally using the current code (this also works for me).

**Comment by zeromonad** [comment]
> Just wanted to mention I have run this on an esp-wroom-32 (pcb antenna), and on an esp-wroom-32u (external antenna), and have no such issues. My only suggestion would be try clearing web cache/cookies if you are using the online configurator. Also you can try installing the web config locally using the current code (this also works for me).

I've tried running it locally with npm on a clean version of Chrome, with cookies + cache cleared in an incognito tab and I'm still running into the same issues unfortunately. No errors in console besides some of the map tiles failing and throwing a 503. The value passed down to the `handleSerialValue` method does not seem to be correct and not the lat long coordinates I chose in the configurator:
![image](https://github.com/flyandi/SquidRID/assets/24425249/61cfd192-486e-42ee-b2f6-374056b2ea2c)

**Comment by Stevofpv** [comment]
> Just wanted to mention I have run this on an esp-wroom-32 (pcb antenna), and on an esp-wroom-32u (external antenna), and have no such issues. My only suggestion would be try clearing web cache/cookies if you are using the online configurator. Also you can try installing the web config locally using the current code (this also works for me).

I ordered the 32u esp you mentioned.   I did find several posts unrelated to this sketch discussing an issue with saving preferences to the spiff with the current board I’m using ( xiao esp32c3) saying it’s a firmware issue on the board.   I’m currently able to upload the sketch but configuring outside of ardiuno does not save when the board is power cycled.   I have the partitions setup correctly and even tried reflashing the firmware from the manufactures site.  I’m thinking it’s a firmware hardware communication error unrelated to the code or web config.   When I run the config on the web as long as the esp32 is connected to the port and not power cycled I’m able to get most of the preferences on the config page to work correctly.   The profiles page doesn’t config anything for me such as the coordinates.  I’m only able to set the origin using the map page.   The synchronization tab seems to do nothing.  When power cycle all setting go back to default.

**Comment by flyandi** [comment]
I am using the XIAO C3 as well for my testing. I ran into some issues with sometimes the config not saving as well. Now I am very curious. Can you link those articles?

**Comment by Stevofpv** [comment]
> I am using the XIAO C3 as well for my testing. I ran into some issues with sometimes the config not saving as well. Now I am very curious. Can you link those articles?

https://forums.adafruit.com/viewtopic.php?t=191923

This was one post mentioning pretty much what seems to be occurring when I try using the configurator.

**Comment by Stevofpv** [comment]
Got my xiao esp32s3 board and uploaded as well as configured via web same as before.  It seems like it’s saving config after power cycle.  Only issue seems to be showing unknown uas ids.  
![IMG_2898](https://github.com/flyandi/SquidRID/assets/138508949/e6d8e2a4-34ad-4296-a66a-1d7206b12045)

**Comment by truglodite** [comment]
You should probably open a separate issue about the Unkown UAS ID thing. I see that on my iphone too... for the split second before the app crashes, sometimes I can see Unknown UAS ID as well.

Also, this issue appears to be directly related to issue #4.

**Comment by flyandi** [comment]
The unknown UAS ID is normal. OpenDroneMap saves the ID and name even it doesn't see frames - other apps don't save it and if they don't receive updated frames they revert to the default display. Nothing I can do. In pest mode, the spawn rate is limited to the set time and once expired, the frames don't update for that anymore.

Maybe worth spending some time in making a secondary pest mode that just spawns n amount of drones and then just cycles them repeatedly through, so that the apps don't get confused. There will be just a limit on how many.
