### ISSUE TITLE
FC GPS Data?

### ISSUE THREAD

**Issue by truglodite** [flyandi/SquidRID#8]
The features list includes `[ ] Supports configurable external sensors such as GPS and Flight Controllers (via LTM Telemetry protocol)`. Does the GPS parser handle MSP... or is something else needed to get coords from an FC?

I'd be grateful if you can give any insight on getting FC coords working with Beta/iNav/Ardu. Honestly all the rigs I'd use it on could care less about the weight of a second gps, but that just doesn't make much sense.

**Comment by flyandi** [comment]
Howdy. Use an unused port and select as Telemetry output with LTM protocol in Betaflight/EMU/whatever. 

It works the same as GPS. Just parses the LTM frames and uses those instead of the simulated values.

**Comment by truglodite** [comment]
Perfect, thanks you very much! Using 9600 baud for this makes even more sense now.
